### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by louw9669** [kantlivelong/OctoPrint-GCodeSystemCommands#11]
I created a script on my Pi that toggles a pin connected to the reset button on the controller board. the script works fine but when I try to use Gxx (xx=any number) to run /usr/local/bin/reset.sh it does nothing. I get an OK in the terminal but no reset. I'm assuming I cant use any Gcode, it would have to be unassigned, correct? what am I doing wrong?

**Comment by kantlivelong** [comment]
Right now gcode parameters aren't passed but there is a PR open that I intend to merge at some point.

For now just create two gcode commands and either embed the value in the script or put it as the command line in the configuration.

**Comment by louw9669** [comment]
I think I may be mistaken on how this works then. what is the OCTO value that we enter? I thought when you type G then the octo number in the terminal it runs the script thats assigned. am I right?


-------- Original Message --------
Subject: Re: [kantlivelong/OctoPrint-GCodeSystemCommands] Just not
working (#11)

**Comment by kantlivelong** [comment]
The number is just the suffix of the virtual GCODE command:

IE:
111 = /bin/ls

Command would be `OCTO111`

**Comment by louw9669** [comment]
I got it now. I'll have to try it when I get a chance. Thanks for the info.On Mar 5, 2018 7:18 PM, Shawn Bruce <notifications@github.com> wrote:The number is just the suffix of the virtual GCODE command:
IE:
111 = /bin/ls
Command would be OCTO111
