### ISSUE TITLE
Don't understand how it's working

### ISSUE THREAD

**Issue by GeanyL** [kantlivelong/OctoPrint-GCodeSystemCommands#12]
Hi !

I don't understand how I must use the plugin.

What the number after OCTO means ? How "activate" this command?

Thank you.

(Project: https://discourse.octoprint.org/t/file-with-information-of-axe-z/1925 & https://discourse.octoprint.org/t/conditions-and-communications-between-2-printers/1838/4)

**Comment by kantlivelong** [comment]
See #7

**Comment by Shinnifura** [comment]
Thank you @kantlivelong  !
