### ISSUE TITLE
Explore adding variables to command definitions

### ISSUE THREAD

**Issue by kantlivelong** [kantlivelong/OctoPrint-GCodeSystemCommands#3]
Title explains it all.

Ref #2

**Comment by b-morgan** [comment]
I'll second this request! I have a Pi Hat to control external 12v fans and I want the speed of those fans to mirror M106 S<n> (and M107 fan off) with <n> = 0-255.

**Comment by pyr0ball** [comment]
Thirded.

I created a python script to control a NeoPixel strip using command line arguments:

Example:
`sudo python /home/octopi/NeoPixel_Control.py -m -r 150 -g 150 -b 150`

**Comment by kantlivelong** [comment]
So this is now in 1.0.0. Arguments are passed to commands as environment variables. If you are calling a binary directly you will need to write a wrapper to parse the arguments safely.
