### ISSUE TITLE
GCODE Scripts and GCODE System Commands

### ISSUE THREAD

**Issue by franzbischoff** [kantlivelong/OctoPrint-GCodeSystemCommands#5]
Hello!

There is any way to use GCODE Scripts tab (e.g.: before disconnect, send OCTO 10) and this trigger a System Command?

Thanks.

**Comment by kantlivelong** [comment]
It should work. Please note that there should not be a space in between OCTO and the number.

Example:
**OCTO10**

**Comment by franzbischoff** [comment]
yes, it works... the mistake was the space between the OCTO and the number.

Thank you.


--
Francisco Bischoff


*"O mate está para o gaúcho como o chá para os ingleses, a coca para os
bolivianos, o uísque para os escoceses e o café... para os brasileiros"--
Eduardo Bueno*

**Comment by kantlivelong** [comment]
No prob.
