### ISSUE TITLE
Excuse the ignorance but....

### ISSUE THREAD

**Issue by bolsoncerrado** [kantlivelong/OctoPrint-GCodeSystemCommands#6]
...would the flow be:

1) Install this plugin
2) define "Gcodes" (OCTO 10, OCTO 20,...)
3) edit (for example) END GCODE on the slicer program and add OCTO 20?

I ask because the gcode will be sent to the firmware instead, right?

Or this plugin will intercept, execute and VOID the firmware call?

**Comment by kantlivelong** [comment]
Correct. The plugin will intercept the psuedo-gcode and not send it to the printer. 

This is not compatible with SD print.

**Comment by bolsoncerrado** [comment]
Cool!!!
How could I launch my already created PRINTER OFF command (which triggers a WeMo switch ON/OFF) only after cooldown (aka Tool temp < 50ºC) ?
 
Any ideas?

**Comment by kantlivelong** [comment]
Sounds like this would be better handled by my [PSUControl](https://github.com/kantlivelong/OctoPrint-PSUControl) plugin as it has that functionality already :smile:

**Comment by bolsoncerrado** [comment]
That sounds nice, so can your plugin choose to launch a .sh instead? :)

**Comment by kantlivelong** [comment]
Yep. Check the docs.

**Comment by bolsoncerrado** [comment]
Awesome thanks!
